Repository GDGoC-Success-Seollyongdan/GDGoC-Success-Seollyongdan-frontend, pull requests merged in 2025-02, with the labels that each got.

#2 [UI] 로그인 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SignUpScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/navigation/CommunityNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/example/screen/ExampleScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/guide/navigation/GuideNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/guide/screen/GuideScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/navigation/MainNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainActivity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/navigation/MypageNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/screen/MypageScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/navigator/SeollyongdanNavHost.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/navigation/SearchNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/screen/SearchScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/AuthButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/AuthTextField.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/BottomNavigationItem.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/theme/Color.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/theme/Theme.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/theme/Type.kt
  app/src/main/res/drawable/ic_login_smile.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 서연 🍀, UI

#5 [FEAT] 회원가입 화면 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/example/seollyongdan_frontend/app/Qualifier.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/RetrofitModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/DataSourceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/Qualifier.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RepositoryModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RetrofitModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/ServiceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/intercepter/RegionIntercepter.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/RegionDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/RegionDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/RegionResponseDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/RegionRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/ApiKeyStorage.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/RegionApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/RegionRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/RegionSearchBottomSheet.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/RegionViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SignUpDuplicationViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SignUpScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/AuthTextField.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SignUpButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SignUpDuplcationCheckButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SignUpIdNicknameTextField.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SignUpPasswordTextField.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SignUpRegionTextField.kt
  app/src/main/res/drawable/ic_back.xml
  gradle.properties
Labels: 서연 🍀, FEAT, UI

#8 [FEAT] 메인 페이지 보완
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/navigation/HomeNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetLifeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetMainScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetRealEstateScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetReviewScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSafetyScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSwitcher.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetTrafficScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/life/navigation/LifeNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/life/navigation/LifeNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/life/screen/LifeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/navigator/SeollyongdanNavHost.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/realestate/navigation/RealEstateNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/realestate/navigation/RealEstateNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/realestate/screen/RealEstateScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/review/navigation/ReviewNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/review/navigation/ReviewNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/review/screen/ReviewScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/safety/navigation/SafetyNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/safety/navigation/SafetyNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/safety/screen/SafetyScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/traffic/navigation/TrafficNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/traffic/navigation/TrafficNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/traffic/screen/TrafficScreen.kt
Labels: 서연 🍀, FEAT

#13 [FEAT] 메인 페이지 부동산, 생활/편의시설, 리뷰 및 별점 페이지 구현
  app/build.gradle.kts
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetLifeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetRealEstateScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetReviewScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSafetyScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSwitcher.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/BarGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/LifeTable.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/LineGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/MainToVisualizationButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/PieGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/SafetyTable.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/UserReview.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/theme/Color.kt
  app/src/main/res/drawable/ic_back_brown.xml
  app/src/main/res/drawable/ic_go.xml
  settings.gradle.kts
Labels: 현진 🌸, FEAT, UI

#18 [Feat] 검색(추천)페이지 구현
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/navigation/SearchNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/navigation/SearchNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/screen/BottomSheetSearchFilter.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/screen/SearchResultScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/screen/SearchScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/DistrictButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/DistrictGroupButton.kt
  app/src/main/res/drawable/ic_search_book.png
  app/src/main/res/drawable/ic_search_coin.png
  app/src/main/res/drawable/ic_search_cup.png
  app/src/main/res/drawable/ic_search_fire.png
  app/src/main/res/drawable/ic_search_puzzle.png
  app/src/main/res/drawable/ic_search_sun.png
  app/src/main/res/drawable/ic_search_wallet.png
Labels: 현진 🌸, FEAT, UI

#20 [FEAT] 회원가입 & 로그인 관련 api 연동
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/example/seollyongdan_frontend/app/di/DataSourceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/PreferencesModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RepositoryModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RetrofitModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/ServiceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/AuthDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/AuthDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/SeollyongdanBaseResponse.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/request/RequestLoginDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/request/RequestSignUpDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseLoginDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseSignUpDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/ApiKeyStorage.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/AuthApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/AuthRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/LoginViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SignUpScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SignUpViewModel.kt
Labels: 서연 🍀, FEAT

#24 [FEAT] UI 관련 디테일 추가
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/seollyongdan_frontend/app/di/DataSourceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/PreferencesModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RepositoryModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RetrofitModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/ServiceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/intercepter/TokenIntercepter.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/HomeDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/HomeDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseHomeSafetyDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/ApiKeyStorage.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/HomeApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/HomeRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/LoginViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/SplashScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/guide/screen/GuideScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetMainScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSafetyScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSwitcher.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/UserEntity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/townIdtotownName.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/navigation/MypageNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/screen/MypageScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/screen/MypageViewModel.kt
  app/src/main/res/drawable/ic_home.png
  app/src/main/res/drawable/ic_nav_comm.xml
  app/src/main/res/drawable/ic_nav_comm_unselected.xml
  app/src/main/res/drawable/ic_nav_guide.xml
  app/src/main/res/drawable/ic_nav_guide_unselected.xml
  app/src/main/res/drawable/ic_nav_home.xml
  app/src/main/res/drawable/ic_nav_home_unselected.xml
  app/src/main/res/drawable/ic_nav_search.xml
  app/src/main/res/drawable/ic_nav_search_unselected.xml
  app/src/main/res/drawable/ic_nav_setting.xml
  app/src/main/res/drawable/ic_nav_setting_unselected.xml
Labels: 서연 🍀, UI

#25 [FEAT] 홈 - 교통, 안전 및 치안, 시각화(임시) 페이지 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/HomeDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/HomeDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseHomeCongestionDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseHomeCrimeFrepDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseHomeTrafficDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/ApiKeyStorage.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/HomeApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/HomeRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/navigation/HomeNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSwitcher.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetTrafficScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyVisualizationScreen_temp.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyVisualizationViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficVisualizationScreen_temp.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficVisualizationViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/CrimeBox.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/DistrictWrapBox.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/MainToVisualizationButton.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/TrafficTable.kt
Labels: 서연 🍀, FEAT, UI

#28 [FEAT] 홈 관련 api 연동 마무리
  app/src/main/java/com/example/seollyongdan_frontend/app/di/DataSourceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/RepositoryModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/app/di/ServiceModule.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/CommunityDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasource/UserDataSource.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/CommunityDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/datasourceimpl/UserDataSourceImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ReponseCommunityPostsDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/dto/response/ResponseUserDto.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/ApiKeyStorage.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/CommunityApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/data/service/UserApiService.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/domain/repository/UserRepository.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/auth/screen/RegionSearchBottomSheet.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/navigation/CommunityNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/navigation/CommunityNavigator.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityDetailScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityLatestScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityPopularScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityPostDetailEntity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityPostEntity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityPostViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunityScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/community/screen/CommunitySearchScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/guide/screen/GuideScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetSafetyScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/BottomSheetTrafficScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/HomeViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyVisualizationScreen_temp.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/SafetyVisualizationViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficVisualizationScreen_temp.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/home/screen/TrafficVisualizationViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainActivity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/MainViewModel.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/main/screen/UserEntity.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/mypage/screen/MypageScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/navigation/SearchNavGraph.kt
  app/src/main/java/com/example/seollyongdan_frontend/presentation/search/screen/SearchScreen.kt
  app/src/main/java/com/example/seollyongdan_frontend/ui/component/PieGraph.kt
Labels: 서연 🍀, FEAT
